### ISSUE TITLE
Create a simple docker regtest environment

### ISSUE THREAD

**Issue by justinmoon** [hkjn/lnhw#20]
One of our biggest problems during the hackathon was getting real c-lightning data as we waited for our bitcoind and c-lightning testnet nodes to finish syncing.

I propose we use something like https://github.com/PierreRochard/bitcoin-lightning-docker to create a dockerized bitcoind / c-lightning test environment running on regtest. This way we wouldn't have to deal with testnet annoyances like coin faucets or syncing testnet's 15gb chain.

The project I linked above uses lnd. I plan to add c-lightning soon. This would probably be sufficient for UI developers. Next we would have to add some ability to use a c-lighting fork, instead.

**Comment by hkjn** [comment]
Good idea @superquest!

Possibly useful as a reference, here is the Dockerfile I use to compile and run bitcoind and lightnind in a container:

* https://github.com/hkjn/src/blob/master/bitcoin/Dockerfile

**Comment by GustavoRSSilva** [comment]
I was looking into c-lightning and found their official [hub.docker page](https://hub.docker.com/r/elementsproject/lightningd/) unfortunately on of the links is broken, but we can still the the docker-compose.yml.


```
version: "3"
services:
  bitcoind:
    image: nicolasdorier/docker-bitcoin:0.16.0
    environment:
      BITCOIN_EXTRA_ARGS: |
        testnet=1
        whitelist=0.0.0.0/0
        server=1
        rpcuser=rpcuser
        rpcpassword=rpcpass
    expose:
      - "18332"
    volumes:
      - "bitcoin_datadir:/data"

  clightning_bitcoin:
    image: elementsproject/lightningd
    command:
      - lightningd
      - --bitcoin-rpcconnect=bitcoind
      - --bitcoin-rpcuser=rpcuser
      - --bitcoin-rpcpassword=rpcpass
      - --network=testnet
      - --alias=myawesomenode
      - --log-level=debug
    environment:
      EXPOSE_TCP: "true"
    expose:
      - "9735"
    volumes:
      - "clightning_bitcoin_datadir:/root/.lightning"
      - "bitcoin_datadir:/etc/bitcoin"
    links:
      - bitcoind

volumes:
  bitcoin_datadir:
  clightning_bitcoin_datadir:
```
